version: "3"

services:
  db:
    image: postgres:12-alpine
    env_file:
      .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
  app:
    build:
      dockerfile: docker/Dockerfile
      context: .
    env_file:
      - .env
    volumes:
      - ./src/:/app/
    ports:
      - "8000:8000"
  app-test:
    build:
      dockerfile: docker/Dockerfile-test
      context: .
    env_file:
      - .env
    profiles:
      - dev
    depends_on:
      - db
volumes:
  data:
